mode: ETH-XGaze
device: cuda
model:
  name: resnet18
face_detector:
  mode: mediapipe
#  dlib_model_path: data/dlib/shape_predictor_68_face_landmarks.dat
  mediapipe_max_num_faces: 1
gaze_estimator:
  checkpoint: models/eth-xgaze_resnet18.pth
  camera_params: data/calib/sample_params.yaml
#  use_dummy_camera_params: false
  normalized_camera_params: data/normalized_camera_params/eth-xgaze.yaml
  normalized_camera_distance: 0.6
  image_size: [224, 224]
demo:
  use_camera: true
  camera_num: 0
  display_on_screen: true
  wait_time: 1
#  image_path: null
  video_path: null
  output_dir: null
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.10
  show_bbox: False
  show_head_pose: True
  show_landmarks: False
#  show_normalized_image: False
  show_template_model: False
